#ifndef REGALLOC_CONFIG_H
#define REGALLOC_CONFIG_H

#define GPR_K 7
#define FLOAT_K 7

#define REGALLOC_COALESCING_ENABLED 1
#define REGALLOC_LOOP_WEIGHT_ENABLED 1
#define REGALLOC_PRESSURE_WEIGHT_ENABLED 0

#endif /* REGALLOC_CONFIG_H */
