/* Auto-generated by scratch/extract_agent_dag.py */
#ifndef TEST_DAG_DATA_H
#define TEST_DAG_DATA_H

#include "../src/zcc_dag.h"

static void init_agent_test_dag(BuildDAG *dag) {
    dag->num_nodes = 17;
    dag->dag_hash = 0xDECAFBADULL;

    /* Node 0: enhanced-agents/adaptability-agent.js */
    strcpy(dag->nodes[0].name, "enhanced-agents/adaptability-agent.js");
    dag->nodes[0].state = 0;
    dag->nodes[0].input_hash = 0x12efb91350368cf6ULL;
    dag->nodes[0].output_hash = 0xc5486a96f694e5fULL;
    dag->nodes[0].num_dependencies = 1;
    dag->nodes[0].dependencies[0] = 16;

    /* Node 1: enhanced-agents/adaptability-assistant.js */
    strcpy(dag->nodes[1].name, "enhanced-agents/adaptability-assistant.js");
    dag->nodes[1].state = 0;
    dag->nodes[1].input_hash = 0xc178e323eeb14d57ULL;
    dag->nodes[1].output_hash = 0x82170d916ff7fd40ULL;
    dag->nodes[1].num_dependencies = 1;
    dag->nodes[1].dependencies[0] = 16;

    /* Node 2: enhanced-agents/adaptability-background.js */
    strcpy(dag->nodes[2].name, "enhanced-agents/adaptability-background.js");
    dag->nodes[2].state = 0;
    dag->nodes[2].input_hash = 0xeca921b45b4145efULL;
    dag->nodes[2].output_hash = 0x317a8d4afa3aae71ULL;
    dag->nodes[2].num_dependencies = 1;
    dag->nodes[2].dependencies[0] = 16;

    /* Node 3: enhanced-agents/adaptability-helper.js */
    strcpy(dag->nodes[3].name, "enhanced-agents/adaptability-helper.js");
    dag->nodes[3].state = 0;
    dag->nodes[3].input_hash = 0x15a7f71503fd8681ULL;
    dag->nodes[3].output_hash = 0xb2216d712dadb154ULL;
    dag->nodes[3].num_dependencies = 1;
    dag->nodes[3].dependencies[0] = 16;

    /* Node 4: enhanced-agents/adaptability-leader.js */
    strcpy(dag->nodes[4].name, "enhanced-agents/adaptability-leader.js");
    dag->nodes[4].state = 0;
    dag->nodes[4].input_hash = 0x174ef31f0bface3dULL;
    dag->nodes[4].output_hash = 0x825c458ced57d45bULL;
    dag->nodes[4].num_dependencies = 1;
    dag->nodes[4].dependencies[0] = 16;

    /* Node 5: enhanced-agents/adaptability-manager.js */
    strcpy(dag->nodes[5].name, "enhanced-agents/adaptability-manager.js");
    dag->nodes[5].state = 0;
    dag->nodes[5].input_hash = 0x5aae1dd500af78e0ULL;
    dag->nodes[5].output_hash = 0x35dc405295d0b630ULL;
    dag->nodes[5].num_dependencies = 1;
    dag->nodes[5].dependencies[0] = 16;

    /* Node 6: enhanced-agents/adaptability-observer.js */
    strcpy(dag->nodes[6].name, "enhanced-agents/adaptability-observer.js");
    dag->nodes[6].state = 0;
    dag->nodes[6].input_hash = 0x4e8b522a2e51ce6aULL;
    dag->nodes[6].output_hash = 0x75d789ab2ff336a8ULL;
    dag->nodes[6].num_dependencies = 1;
    dag->nodes[6].dependencies[0] = 16;

    /* Node 7: enhanced-agents/adaptability-recycle.js */
    strcpy(dag->nodes[7].name, "enhanced-agents/adaptability-recycle.js");
    dag->nodes[7].state = 0;
    dag->nodes[7].input_hash = 0xf32688099211c5b8ULL;
    dag->nodes[7].output_hash = 0xc930316b798e2f49ULL;
    dag->nodes[7].num_dependencies = 1;
    dag->nodes[7].dependencies[0] = 16;

    /* Node 8: enhanced-agents/adaptability-regen.js */
    strcpy(dag->nodes[8].name, "enhanced-agents/adaptability-regen.js");
    dag->nodes[8].state = 0;
    dag->nodes[8].input_hash = 0x2bf7827b520a0dcfULL;
    dag->nodes[8].output_hash = 0xf50a871c145c9d95ULL;
    dag->nodes[8].num_dependencies = 1;
    dag->nodes[8].dependencies[0] = 16;

    /* Node 9: enhanced-agents/adaptability-superintendent.js */
    strcpy(dag->nodes[9].name, "enhanced-agents/adaptability-superintendent.js");
    dag->nodes[9].state = 0;
    dag->nodes[9].input_hash = 0x68d99f0536d82823ULL;
    dag->nodes[9].output_hash = 0xf4da41240e698bcaULL;
    dag->nodes[9].num_dependencies = 1;
    dag->nodes[9].dependencies[0] = 16;

    /* Node 10: enhanced-agents/adaptability-supervisor.js */
    strcpy(dag->nodes[10].name, "enhanced-agents/adaptability-supervisor.js");
    dag->nodes[10].state = 0;
    dag->nodes[10].input_hash = 0xcad7d8753ca96721ULL;
    dag->nodes[10].output_hash = 0x73dcd68998641d6bULL;
    dag->nodes[10].num_dependencies = 1;
    dag->nodes[10].dependencies[0] = 16;

    /* Node 11: enhanced-agents/adaptability-worker.js */
    strcpy(dag->nodes[11].name, "enhanced-agents/adaptability-worker.js");
    dag->nodes[11].state = 0;
    dag->nodes[11].input_hash = 0x19ce56dee3a2325dULL;
    dag->nodes[11].output_hash = 0xd5068e04a5657181ULL;
    dag->nodes[11].num_dependencies = 1;
    dag->nodes[11].dependencies[0] = 16;

    /* Node 12: enhanced-agents/adaptive-hurst-tracker.js */
    strcpy(dag->nodes[12].name, "enhanced-agents/adaptive-hurst-tracker.js");
    dag->nodes[12].state = 0;
    dag->nodes[12].input_hash = 0xb8f4de334d270cd8ULL;
    dag->nodes[12].output_hash = 0x7e5048e096129401ULL;
    dag->nodes[12].num_dependencies = 1;
    dag->nodes[12].dependencies[0] = 15;

    /* Node 13: enhanced-agents/adaptive-ui-ux-agent.js */
    strcpy(dag->nodes[13].name, "enhanced-agents/adaptive-ui-ux-agent.js");
    dag->nodes[13].state = 0;
    dag->nodes[13].input_hash = 0x37fb65ce83432e6cULL;
    dag->nodes[13].output_hash = 0x8671edacb10f2bfbULL;
    dag->nodes[13].num_dependencies = 1;
    dag->nodes[13].dependencies[0] = 16;

    /* Node 14: enhanced-agents/agent-factory.js */
    strcpy(dag->nodes[14].name, "enhanced-agents/agent-factory.js");
    dag->nodes[14].state = 0;
    dag->nodes[14].input_hash = 0x1ffdb0633b525b22ULL;
    dag->nodes[14].output_hash = 0x3b4372db4a1cfc34ULL;
    dag->nodes[14].num_dependencies = 1;
    dag->nodes[14].dependencies[0] = 16;

    /* Node 15: enhanced-agents/hurst-zkaedi-synthesis.js */
    strcpy(dag->nodes[15].name, "enhanced-agents/hurst-zkaedi-synthesis.js");
    dag->nodes[15].state = 0;
    dag->nodes[15].input_hash = 0x1ea7ed8647a26bd9ULL;
    dag->nodes[15].output_hash = 0x935ea212b1fbe12ULL;
    dag->nodes[15].num_dependencies = 0;

    /* Node 16: enhanced-agents/utils/logger.js */
    strcpy(dag->nodes[16].name, "enhanced-agents/utils/logger.js");
    dag->nodes[16].state = 0;
    dag->nodes[16].input_hash = 0x5ef1e7ca864a5372ULL;
    dag->nodes[16].output_hash = 0xcc64f898f8156befULL;
    dag->nodes[16].num_dependencies = 0;

}
#endif /* TEST_DAG_DATA_H */